services:
  science-gpt:
    container_name: science-gpt-app
    build:
      context: ./
    expose:
      - "8501"
    volumes:
      - ./app/vectorstore:/usr/src/app/vectorstore
    networks:
      - app-network
      - milvus
    environment:
      - DEV_MODE=${DEV_MODE:-false}
    restart: always
    depends_on:
      standalone:
        condition: service_healthy
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: science-gpt-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - science-gpt
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
  milvus:
    external: true