services:
  science-gpt:
    container_name: science-gpt-app
    build:
      context: ./
      args:
        - UPDATE_DEPS=${UPDATE_DEPS:-false}
    expose:
      - "8501"
    volumes:
      - ./app/vectorstore:/usr/src/app/vectorstore
    networks:
      - app-network
      - milvus
    environment:
      - DEV_MODE=${DEV_MODE:-false}
    restart: unless-stopped
    depends_on:
      standalone:
        condition: service_healthy
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              device_ids: ["0"] # Change "0" to the desired GPU ID if needed

  nginx:
    image: nginx:latest
    container_name: science-gpt-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - science-gpt
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
  milvus:
    external: true