services:
  science-gpt:
    image: science-gpt
    expose:
      - "8501"
    volumes:
      - ./app/vectorstore:/usr/src/app/vectorstore
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - science-gpt
    networks:
      - app-network

networks:
  app-network:
    driver: bridge