_target_: orchestrator.config.SystemConfig
model_name: gpt-3.5

model_params:
  seed: "42"
  temperature: 0
  max_tokens: 512
  top_p: 1
  num_ctx: 2500

model_auth:
  macbook_endpoint:
  url: 
  api_key: 
  version: 

extraction:
  pdf_extract_method: "pypdf2"

chunking:
  method: "split_sentences"

embedding:
  method: "huggingface-sentence-transformer"
  model: "sentence-transformers/all-mpnet-base-v2"

vector_db:
  type: "local-chromadb"
  local_path: "chroma"
  instance_name: "chromadb-instance"
  search_strategy: "similarity"

rag_params:
  top_k_retrieval: 5

