_target_: orchestrator.config.SystemConfig
model_name: gpt-3.5

model_params:
  seed: 42
  temperature: 0.0
  top_p: 0.2
  max_tokens: 512
  num_ctx: 2500

model_auth:
  macbook_endpoint:
  url: 
  api_key: 
  version: 

extraction:
  pdf_extract_method: "pypdf2"

chunking:
  method: "recursive_character"

embedding:
  model: "all-mpnet-base-v2"

vector_db:
  type: "milvus"
  host: "standalone"
  port: 19530

rag_params:
  top_k_retrieval: 5
