# Guide to the System Config!
#
# This config is responsible for initializing the app with default parameters.
# At runtime, it becomes a dynamic object that is updated in real time to reflect the internal state of the app.
#
# The config also maintains the list of supported extraction methods, chunking strategies, embedding models, databases, RAG techniques, and chat models. 
# When a new feature is added to the app, the corresponding parameter should be added to the system config.

_target_: orchestrator.config.SystemConfig

# Model Config Options
model_params:
  supported_models:
    - "llama3:latest"
    - "GPT-4.0"
    - "GPT-3.5"
  model: "GPT-3.5"
  seed: 42
  temperature: 0.0
  top_p: 1.0
  max_tokens: 512
  num_ctx: 2500
        
model_auth:
  macbook_endpoint:
  url: 
  api_key: 
  version: 

# Document Processing Options
extraction:
  supported_extractors:
    - "pypdf2"
    - "pymupdf"
    - "pymypdf4llm"
  extraction_method: "pypdf2"

chunking:
  supported_chunkers:
    - "recursive_character"
    - "recursive_character:large_chunks"
    - "recursive_character:small_chunks"
  chunking_method: "recursive_character"

embedding:
  supported_embedders:
    - "mxbai-embed-large"
    - "nomic-embed-text"
  embedding_model: "mxbai-embed-large"

# Database Options
vector_db:
  supported_databases:
    - "chromadb"
    - "milvus"
  database: "chromadb"
  host: "standalone"
  port: 19530

# Default RAG Parameters
rag_params:
  top_k_retrieval: 5
  keywords:



