cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    bhux:
      email: bing.hu@phac-aspc.gc.ca
      first_name: Bing
      last_name: Hu
      logged_in: false
      password: $2b$12$2VY7SFAKVbw/n5bqf2kZB.q9NafpgDYzShHYlIb1y.ZTMmJz57B6u
      password_hint: '-'
      roles: null
    j55zhong:
      email: jiaiyou.zhong@hc-sc.gc.ca
      first_name: Jiayou
      last_name: Zhong
      logged_in: false
      password: $2b$12$XbUz6uuCRYYtBBHfCX0keeQdhZ53EYdQV19GRkEoPQhFLQLFmqtey
      password_hint: '1'
      roles: null
    spcrook:
      email: spencer.crook@hc-sc.gc.ca
      first_name: spencer
      last_name: crook
      logged_in: false
      password: $2b$12$6.vxJLGmt5flR2oh2dtUGe5q74PkchgwK33dBsdW/E6xB0GE6/Fjq
      password_hint: 'no'
      roles: null
pre-authorized:
  emails:
  - adam.aitchison@hc-sc.gc.ca
  - suzanne.butt@hc-sc.gc.ca
  - amanda.carlow@hc-sc.gc.ca
  - haris.gisavi@hc-sc.gc.ca
  - chantal.medina@hc-sc.gc.ca
  - malik.talhat@hc-sc.gc.ca
  - carter.demars@hc-sc.gc.ca
  - serena.iyoha@hc-sc.gc.ca
  - jiaiyou.zhong@hc-sc.gc.ca
